### PR TITLE
Interceptor to stop requests when the application is not ready

### PR DESCRIPTION
**Pull request by thiagodpf**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

feature

* **What is the current behavior?** (You can also link to an open issue here)

The application, even if not ready, accepts requests. This behavior can put the application in an undetermined state.

* **What is the new behavior (if this is a feature change)?**

The application starts accepting requests only when _ServiceStateManager_ finds that all the exceptional services that the application uses are in readiness.

There is a bypass when the `NODE_ENV` environment variable is set to `development`, in this case, the interceptor stops working.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

no

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

no

* **Other information**:

### CODE REVIEW

**Review by mprevide — APPROVED** [review]
Nice :1st_place_medal: 

Sometimes I just think the term "Ready" to be used in heathcheck a bit confusing, but it is something from the library.

Only more tests are needed.

**Comment by thiagodpf** [comment]
@mprevide the _lightship_ component provides 3 endpoints for the kubernetes. Are they: `'/health'`, `'/live'` and `'/ready'`
I'm not sure why we started using the `'/ready'` endpoint. Maybe @andersonluisribeiro can explain it to us at another time.

I believe the explanation can be found [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/). I think we need to work on these endpoints better, because sometimes the intention is for the k8s to kill the pod instead of waiting for it to be ready. 

Good observation yours :+1:

**Comment by thiagodpf** [comment]
@rascaraficci i included script `lib/webUtils/createTokenGen.js` according to your suggestion in PR [dojot/dojot#1980](https://github.com/dojot/dojot/pull/1980). I believe it can be useful until we change the way the _tenant_ travels between services.

**Comment by mprevide** [comment]
> @mprevide the _lightship_ component provides 3 endpoints for the kubernetes. Are they: `'/health'`, `'/live'` and `'/ready'`
> I'm not sure why we started using the `'/ready'` endpoint. Maybe @andersonluisribeiro can explain it to us at another time.
> 
> I believe the explanation can be found [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/). I think we need to work on these endpoints better, because sometimes the intention is for the k8s to kill the pod instead of waiting for it to be ready. 
> 
> Good observation yours :+1: 
> 
> 

Yes, I know a little about this. 

I just think to use "ready" after the pod already is started a little  weird, but yours observations was good =)

**Comment by mprevide** [comment]
> @rascaraficci i included script `lib/webUtils/createTokenGen.js` according to your suggestion in PR [dojot/dojot#1980](https://github.com/dojot/dojot/pull/1980). I believe it can be useful until we change the way the _tenant_ travels between services.

I think it would also be very useful the middleware to parse the jwt and get the service/tenant.

**Review by mprevide — DISMISSED** [review]
I just left a suggestion

**Comment by thiagodpf** [comment]
@mprevide  I included script `lib/webUtils/framework/interceptors/tokenParsingInterceptor.js` according to your suggestion.

**Review by mprevide — APPROVED** [review]
Great job =D

**Review by rascaraficci — APPROVED** [review]
It looks OK!

**Pull request merged**
