### PR TITLE
[config-manager] Add env var support in conf files

### PR DESCRIPTION
**Pull request by eduardogmisiuk**
* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
You can pass an environment variable with a default value in conf files, e.g. `mqtt.username=${HOSTNAME:-v2k-bridge}`.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
https://github.com/dojot/dojot/issues/1765

* **Other information**:

### CODE REVIEW

**Comment by mprevide** [comment]
Can I use this with array of strings ?
And if it is a number or bool, will it work well?

**Comment by eduardogmisiuk** [comment]
> Can I use this with array of strings ?
> And if it is a number or bool, will it work well?

Yes, this should work for these cases. This is a pre processing feature, it will change all the env vars that you set in the conf files before any parsing is done.

**Review by mprevide — APPROVED** [review]

**Comment by mprevide** [comment]
Great job! :1st_place_medal:

**Review by thiagodpf — APPROVED** [review]
:100:

**Pull request merged**
